PROGRAM=myOscilloscope
EXTRA_COMPONENTS = extras/cpp_support
LIBS ?= c gcc hal 
EXTRA_C_CXX_FLAGS =  -fabi-version=5

# PROGRAM_CXXFLAGS = -std=c++11
# EXTRA_CXXFLAGS = -std=c++11
COMPONENTS = FreeRTOS lwip core extras/mbedtls
include ../../../esp2866/esp-open-rtos/common.mk

